#!/bin/bash

set -e
set -u

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE $HISTORY_DB_USER LOGIN PASSWORD '$HISTORY_DB_PASSWORD';
    ALTER ROLE $HISTORY_DB_USER CREATEROLE NOINHERIT;
    GRANT CREATE ON DATABASE $POSTGRES_DB TO $HISTORY_DB_USER;
    CREATE ROLE $POSTGRAPHILE_DB_USER LOGIN PASSWORD '$POSTGRAPHILE_DB_PASSWORD';
    ALTER ROLE $POSTGRAPHILE_DB_USER CREATEROLE NOINHERIT;
    GRANT CREATE ON DATABASE $POSTGRES_DB TO $POSTGRAPHILE_DB_USER;
EOSQL
