#!/bin/bash

set -e
set -u

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE "$ENGINE_DB_USER" LOGIN PASSWORD '$ENGINE_DB_PASSWORD' NOINHERIT;
    GRANT CREATE ON DATABASE "$POSTGRES_DB" TO "$ENGINE_DB_USER";
    --
    CREATE ROLE "$HISTORY_DB_USER" LOGIN PASSWORD '$HISTORY_DB_PASSWORD' NOINHERIT;
    GRANT CREATE ON DATABASE "$POSTGRES_DB" TO "$HISTORY_DB_USER";
    --
    CREATE ROLE "$READ_MODEL_DB_USER" LOGIN PASSWORD '$READ_MODEL_DB_PASSWORD' NOINHERIT;
    GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$READ_MODEL_DB_USER";
EOSQL
