LOCAL_TOKEN_URL = "http://keycloak:11000/realms/nplintegrations/protocol/openid-connect/token"
LOCAL_ROOT_URL = "http://engine:12000"
PAAS_TOKEN_URL = "https://keycloak-pwctraining-nplintegrations.noumena.cloud/realms/nplintegrations/protocol/openid-connect/token"
PAAS_ROOT_URL = "https://engine-pwctraining-nplintegrations.noumena.cloud"
REALM = "nplintegrations"
USERNAME = "bob"
PASSWORD = "bob"
