<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.noumenadigital.npl-integrations</groupId>
    <artifactId>keycloak-plugins</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <keycloak.version>25.0.6</keycloak.version>
        <kotlin.version>2.2.20</kotlin.version>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>san-uri-to-roles-mapper</module>
        <module>mtls-x509-sans-authenticator</module>
    </modules>
</project>