@startuml
namespace processes.settle  {
    class Settle << (p,orchid) >> {
        +iouOwner: Party
        +carOwner:Party
        +iou: Iou
        +car: Car
        +[iouOwner | carOwner] swap()
    }

    Settle --> "1" objects.iou.Iou : iou
    Settle --> "1" objects.car.Car : car
}
@enduml